# ansible-playbook k8s_install.yml -i hosts -u alex -k -K
# 已经安装过docker可以执行ansible-playbook k8s_install.yml -i hosts -u alex -k -K --skip-tags=docker
---
- hosts: k8s
  roles:
    - role: docker
      become: yes
      tags:
        - docker
    - role: k8s_env
      become: yes

- hosts: master
  roles:
    - role: k8s_master
      become: yes

- hosts: node
  roles:
    - role: k8s_node
      become: yes
