docker:
  version: docker-ce-18.09.9-3.el7
  repo: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  registry_mirrors: https://registry.docker-cn.com
  remove_list:
    - docker
    - docker-ce
    - docker-client
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
k8s:
  version: v1.16.0
  master_ip: "{{ hostvars['k8s-master'].ansible_ssh_host }}"
  image_repository: registry.aliyuncs.com/google_containers
  baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
  gpgkey: "https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg"
  pod_netword: 10.244.0.0
  kubectl: kubectl-1.16.0-0
  kubeadm: kubeadm-1.16.0-0
  kubelet: kubelet-1.16.0-0
  flannel:
    path: /tmp/kube-flannel.yml
    image_url: quay.io

